# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /run/media/jpereiratrindade/labeco10T/dev/cpp/vulkan

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /run/media/jpereiratrindade/labeco10T/dev/cpp/vulkan

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /run/media/jpereiratrindade/labeco10T/dev/cpp/vulkan/CMakeFiles /run/media/jpereiratrindade/labeco10T/dev/cpp/vulkan//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /run/media/jpereiratrindade/labeco10T/dev/cpp/vulkan/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hello

# Build rule for target.
hello: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hello
.PHONY : hello

# fast build rule for target.
hello/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/build
.PHONY : hello/fast

#=============================================================================
# Target rules for targets named shaders_spirv

# Build rule for target.
shaders_spirv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shaders_spirv
.PHONY : shaders_spirv

# fast build rule for target.
shaders_spirv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shaders_spirv.dir/build.make CMakeFiles/shaders_spirv.dir/build
.PHONY : shaders_spirv/fast

imgui/backends/imgui_impl_sdl2.o: imgui/backends/imgui_impl_sdl2.cpp.o
.PHONY : imgui/backends/imgui_impl_sdl2.o

# target to build an object file
imgui/backends/imgui_impl_sdl2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/imgui/backends/imgui_impl_sdl2.cpp.o
.PHONY : imgui/backends/imgui_impl_sdl2.cpp.o

imgui/backends/imgui_impl_sdl2.i: imgui/backends/imgui_impl_sdl2.cpp.i
.PHONY : imgui/backends/imgui_impl_sdl2.i

# target to preprocess a source file
imgui/backends/imgui_impl_sdl2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/imgui/backends/imgui_impl_sdl2.cpp.i
.PHONY : imgui/backends/imgui_impl_sdl2.cpp.i

imgui/backends/imgui_impl_sdl2.s: imgui/backends/imgui_impl_sdl2.cpp.s
.PHONY : imgui/backends/imgui_impl_sdl2.s

# target to generate assembly for a file
imgui/backends/imgui_impl_sdl2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/imgui/backends/imgui_impl_sdl2.cpp.s
.PHONY : imgui/backends/imgui_impl_sdl2.cpp.s

imgui/backends/imgui_impl_vulkan.o: imgui/backends/imgui_impl_vulkan.cpp.o
.PHONY : imgui/backends/imgui_impl_vulkan.o

# target to build an object file
imgui/backends/imgui_impl_vulkan.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/imgui/backends/imgui_impl_vulkan.cpp.o
.PHONY : imgui/backends/imgui_impl_vulkan.cpp.o

imgui/backends/imgui_impl_vulkan.i: imgui/backends/imgui_impl_vulkan.cpp.i
.PHONY : imgui/backends/imgui_impl_vulkan.i

# target to preprocess a source file
imgui/backends/imgui_impl_vulkan.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/imgui/backends/imgui_impl_vulkan.cpp.i
.PHONY : imgui/backends/imgui_impl_vulkan.cpp.i

imgui/backends/imgui_impl_vulkan.s: imgui/backends/imgui_impl_vulkan.cpp.s
.PHONY : imgui/backends/imgui_impl_vulkan.s

# target to generate assembly for a file
imgui/backends/imgui_impl_vulkan.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/imgui/backends/imgui_impl_vulkan.cpp.s
.PHONY : imgui/backends/imgui_impl_vulkan.cpp.s

imgui/imgui.o: imgui/imgui.cpp.o
.PHONY : imgui/imgui.o

# target to build an object file
imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/imgui/imgui.cpp.o
.PHONY : imgui/imgui.cpp.o

imgui/imgui.i: imgui/imgui.cpp.i
.PHONY : imgui/imgui.i

# target to preprocess a source file
imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/imgui/imgui.cpp.i
.PHONY : imgui/imgui.cpp.i

imgui/imgui.s: imgui/imgui.cpp.s
.PHONY : imgui/imgui.s

# target to generate assembly for a file
imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/imgui/imgui.cpp.s
.PHONY : imgui/imgui.cpp.s

imgui/imgui_demo.o: imgui/imgui_demo.cpp.o
.PHONY : imgui/imgui_demo.o

# target to build an object file
imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/imgui/imgui_demo.cpp.o
.PHONY : imgui/imgui_demo.cpp.o

imgui/imgui_demo.i: imgui/imgui_demo.cpp.i
.PHONY : imgui/imgui_demo.i

# target to preprocess a source file
imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/imgui/imgui_demo.cpp.i
.PHONY : imgui/imgui_demo.cpp.i

imgui/imgui_demo.s: imgui/imgui_demo.cpp.s
.PHONY : imgui/imgui_demo.s

# target to generate assembly for a file
imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/imgui/imgui_demo.cpp.s
.PHONY : imgui/imgui_demo.cpp.s

imgui/imgui_draw.o: imgui/imgui_draw.cpp.o
.PHONY : imgui/imgui_draw.o

# target to build an object file
imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/imgui/imgui_draw.cpp.o
.PHONY : imgui/imgui_draw.cpp.o

imgui/imgui_draw.i: imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.i

# target to preprocess a source file
imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.cpp.i

imgui/imgui_draw.s: imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.s

# target to generate assembly for a file
imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.cpp.s

imgui/imgui_tables.o: imgui/imgui_tables.cpp.o
.PHONY : imgui/imgui_tables.o

# target to build an object file
imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/imgui/imgui_tables.cpp.o
.PHONY : imgui/imgui_tables.cpp.o

imgui/imgui_tables.i: imgui/imgui_tables.cpp.i
.PHONY : imgui/imgui_tables.i

# target to preprocess a source file
imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/imgui/imgui_tables.cpp.i
.PHONY : imgui/imgui_tables.cpp.i

imgui/imgui_tables.s: imgui/imgui_tables.cpp.s
.PHONY : imgui/imgui_tables.s

# target to generate assembly for a file
imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/imgui/imgui_tables.cpp.s
.PHONY : imgui/imgui_tables.cpp.s

imgui/imgui_widgets.o: imgui/imgui_widgets.cpp.o
.PHONY : imgui/imgui_widgets.o

# target to build an object file
imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/imgui/imgui_widgets.cpp.o
.PHONY : imgui/imgui_widgets.cpp.o

imgui/imgui_widgets.i: imgui/imgui_widgets.cpp.i
.PHONY : imgui/imgui_widgets.i

# target to preprocess a source file
imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/imgui/imgui_widgets.cpp.i
.PHONY : imgui/imgui_widgets.cpp.i

imgui/imgui_widgets.s: imgui/imgui_widgets.cpp.s
.PHONY : imgui/imgui_widgets.s

# target to generate assembly for a file
imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/imgui/imgui_widgets.cpp.s
.PHONY : imgui/imgui_widgets.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/main.cpp.s
.PHONY : main.cpp.s

src/core/application.o: src/core/application.cpp.o
.PHONY : src/core/application.o

# target to build an object file
src/core/application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/core/application.cpp.o
.PHONY : src/core/application.cpp.o

src/core/application.i: src/core/application.cpp.i
.PHONY : src/core/application.i

# target to preprocess a source file
src/core/application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/core/application.cpp.i
.PHONY : src/core/application.cpp.i

src/core/application.s: src/core/application.cpp.s
.PHONY : src/core/application.s

# target to generate assembly for a file
src/core/application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/core/application.cpp.s
.PHONY : src/core/application.cpp.s

src/core/command_pool.o: src/core/command_pool.cpp.o
.PHONY : src/core/command_pool.o

# target to build an object file
src/core/command_pool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/core/command_pool.cpp.o
.PHONY : src/core/command_pool.cpp.o

src/core/command_pool.i: src/core/command_pool.cpp.i
.PHONY : src/core/command_pool.i

# target to preprocess a source file
src/core/command_pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/core/command_pool.cpp.i
.PHONY : src/core/command_pool.cpp.i

src/core/command_pool.s: src/core/command_pool.cpp.s
.PHONY : src/core/command_pool.s

# target to generate assembly for a file
src/core/command_pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/core/command_pool.cpp.s
.PHONY : src/core/command_pool.cpp.s

src/core/graphics_context.o: src/core/graphics_context.cpp.o
.PHONY : src/core/graphics_context.o

# target to build an object file
src/core/graphics_context.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/core/graphics_context.cpp.o
.PHONY : src/core/graphics_context.cpp.o

src/core/graphics_context.i: src/core/graphics_context.cpp.i
.PHONY : src/core/graphics_context.i

# target to preprocess a source file
src/core/graphics_context.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/core/graphics_context.cpp.i
.PHONY : src/core/graphics_context.cpp.i

src/core/graphics_context.s: src/core/graphics_context.cpp.s
.PHONY : src/core/graphics_context.s

# target to generate assembly for a file
src/core/graphics_context.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/core/graphics_context.cpp.s
.PHONY : src/core/graphics_context.cpp.s

src/core/job_system.o: src/core/job_system.cpp.o
.PHONY : src/core/job_system.o

# target to build an object file
src/core/job_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/core/job_system.cpp.o
.PHONY : src/core/job_system.cpp.o

src/core/job_system.i: src/core/job_system.cpp.i
.PHONY : src/core/job_system.i

# target to preprocess a source file
src/core/job_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/core/job_system.cpp.i
.PHONY : src/core/job_system.cpp.i

src/core/job_system.s: src/core/job_system.cpp.s
.PHONY : src/core/job_system.s

# target to generate assembly for a file
src/core/job_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/core/job_system.cpp.s
.PHONY : src/core/job_system.cpp.s

src/core/swapchain.o: src/core/swapchain.cpp.o
.PHONY : src/core/swapchain.o

# target to build an object file
src/core/swapchain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/core/swapchain.cpp.o
.PHONY : src/core/swapchain.cpp.o

src/core/swapchain.i: src/core/swapchain.cpp.i
.PHONY : src/core/swapchain.i

# target to preprocess a source file
src/core/swapchain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/core/swapchain.cpp.i
.PHONY : src/core/swapchain.cpp.i

src/core/swapchain.s: src/core/swapchain.cpp.s
.PHONY : src/core/swapchain.s

# target to generate assembly for a file
src/core/swapchain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/core/swapchain.cpp.s
.PHONY : src/core/swapchain.cpp.s

src/core/sync_objects.o: src/core/sync_objects.cpp.o
.PHONY : src/core/sync_objects.o

# target to build an object file
src/core/sync_objects.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/core/sync_objects.cpp.o
.PHONY : src/core/sync_objects.cpp.o

src/core/sync_objects.i: src/core/sync_objects.cpp.i
.PHONY : src/core/sync_objects.i

# target to preprocess a source file
src/core/sync_objects.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/core/sync_objects.cpp.i
.PHONY : src/core/sync_objects.cpp.i

src/core/sync_objects.s: src/core/sync_objects.cpp.s
.PHONY : src/core/sync_objects.s

# target to generate assembly for a file
src/core/sync_objects.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/core/sync_objects.cpp.s
.PHONY : src/core/sync_objects.cpp.s

src/graphics/camera.o: src/graphics/camera.cpp.o
.PHONY : src/graphics/camera.o

# target to build an object file
src/graphics/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/graphics/camera.cpp.o
.PHONY : src/graphics/camera.cpp.o

src/graphics/camera.i: src/graphics/camera.cpp.i
.PHONY : src/graphics/camera.i

# target to preprocess a source file
src/graphics/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/graphics/camera.cpp.i
.PHONY : src/graphics/camera.cpp.i

src/graphics/camera.s: src/graphics/camera.cpp.s
.PHONY : src/graphics/camera.s

# target to generate assembly for a file
src/graphics/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/graphics/camera.cpp.s
.PHONY : src/graphics/camera.cpp.s

src/graphics/geometry_utils.o: src/graphics/geometry_utils.cpp.o
.PHONY : src/graphics/geometry_utils.o

# target to build an object file
src/graphics/geometry_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/graphics/geometry_utils.cpp.o
.PHONY : src/graphics/geometry_utils.cpp.o

src/graphics/geometry_utils.i: src/graphics/geometry_utils.cpp.i
.PHONY : src/graphics/geometry_utils.i

# target to preprocess a source file
src/graphics/geometry_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/graphics/geometry_utils.cpp.i
.PHONY : src/graphics/geometry_utils.cpp.i

src/graphics/geometry_utils.s: src/graphics/geometry_utils.cpp.s
.PHONY : src/graphics/geometry_utils.s

# target to generate assembly for a file
src/graphics/geometry_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/graphics/geometry_utils.cpp.s
.PHONY : src/graphics/geometry_utils.cpp.s

src/graphics/material.o: src/graphics/material.cpp.o
.PHONY : src/graphics/material.o

# target to build an object file
src/graphics/material.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/graphics/material.cpp.o
.PHONY : src/graphics/material.cpp.o

src/graphics/material.i: src/graphics/material.cpp.i
.PHONY : src/graphics/material.i

# target to preprocess a source file
src/graphics/material.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/graphics/material.cpp.i
.PHONY : src/graphics/material.cpp.i

src/graphics/material.s: src/graphics/material.cpp.s
.PHONY : src/graphics/material.s

# target to generate assembly for a file
src/graphics/material.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/graphics/material.cpp.s
.PHONY : src/graphics/material.cpp.s

src/graphics/mesh.o: src/graphics/mesh.cpp.o
.PHONY : src/graphics/mesh.o

# target to build an object file
src/graphics/mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/graphics/mesh.cpp.o
.PHONY : src/graphics/mesh.cpp.o

src/graphics/mesh.i: src/graphics/mesh.cpp.i
.PHONY : src/graphics/mesh.i

# target to preprocess a source file
src/graphics/mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/graphics/mesh.cpp.i
.PHONY : src/graphics/mesh.cpp.i

src/graphics/mesh.s: src/graphics/mesh.cpp.s
.PHONY : src/graphics/mesh.s

# target to generate assembly for a file
src/graphics/mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/graphics/mesh.cpp.s
.PHONY : src/graphics/mesh.cpp.s

src/graphics/shader.o: src/graphics/shader.cpp.o
.PHONY : src/graphics/shader.o

# target to build an object file
src/graphics/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/graphics/shader.cpp.o
.PHONY : src/graphics/shader.cpp.o

src/graphics/shader.i: src/graphics/shader.cpp.i
.PHONY : src/graphics/shader.i

# target to preprocess a source file
src/graphics/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/graphics/shader.cpp.i
.PHONY : src/graphics/shader.cpp.i

src/graphics/shader.s: src/graphics/shader.cpp.s
.PHONY : src/graphics/shader.s

# target to generate assembly for a file
src/graphics/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/graphics/shader.cpp.s
.PHONY : src/graphics/shader.cpp.s

src/imgui_backend.o: src/imgui_backend.cpp.o
.PHONY : src/imgui_backend.o

# target to build an object file
src/imgui_backend.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/imgui_backend.cpp.o
.PHONY : src/imgui_backend.cpp.o

src/imgui_backend.i: src/imgui_backend.cpp.i
.PHONY : src/imgui_backend.i

# target to preprocess a source file
src/imgui_backend.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/imgui_backend.cpp.i
.PHONY : src/imgui_backend.cpp.i

src/imgui_backend.s: src/imgui_backend.cpp.s
.PHONY : src/imgui_backend.s

# target to generate assembly for a file
src/imgui_backend.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/imgui_backend.cpp.s
.PHONY : src/imgui_backend.cpp.s

src/init_sdl.o: src/init_sdl.cpp.o
.PHONY : src/init_sdl.o

# target to build an object file
src/init_sdl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/init_sdl.cpp.o
.PHONY : src/init_sdl.cpp.o

src/init_sdl.i: src/init_sdl.cpp.i
.PHONY : src/init_sdl.i

# target to preprocess a source file
src/init_sdl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/init_sdl.cpp.i
.PHONY : src/init_sdl.cpp.i

src/init_sdl.s: src/init_sdl.cpp.s
.PHONY : src/init_sdl.s

# target to generate assembly for a file
src/init_sdl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/init_sdl.cpp.s
.PHONY : src/init_sdl.cpp.s

src/math/analysis.o: src/math/analysis.cpp.o
.PHONY : src/math/analysis.o

# target to build an object file
src/math/analysis.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/math/analysis.cpp.o
.PHONY : src/math/analysis.cpp.o

src/math/analysis.i: src/math/analysis.cpp.i
.PHONY : src/math/analysis.i

# target to preprocess a source file
src/math/analysis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/math/analysis.cpp.i
.PHONY : src/math/analysis.cpp.i

src/math/analysis.s: src/math/analysis.cpp.s
.PHONY : src/math/analysis.s

# target to generate assembly for a file
src/math/analysis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/math/analysis.cpp.s
.PHONY : src/math/analysis.cpp.s

src/math/pcoa.o: src/math/pcoa.cpp.o
.PHONY : src/math/pcoa.o

# target to build an object file
src/math/pcoa.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/math/pcoa.cpp.o
.PHONY : src/math/pcoa.cpp.o

src/math/pcoa.i: src/math/pcoa.cpp.i
.PHONY : src/math/pcoa.i

# target to preprocess a source file
src/math/pcoa.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/math/pcoa.cpp.i
.PHONY : src/math/pcoa.cpp.i

src/math/pcoa.s: src/math/pcoa.cpp.s
.PHONY : src/math/pcoa.s

# target to generate assembly for a file
src/math/pcoa.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/math/pcoa.cpp.s
.PHONY : src/math/pcoa.cpp.s

src/renderer.o: src/renderer.cpp.o
.PHONY : src/renderer.o

# target to build an object file
src/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/renderer.cpp.o
.PHONY : src/renderer.cpp.o

src/renderer.i: src/renderer.cpp.i
.PHONY : src/renderer.i

# target to preprocess a source file
src/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/renderer.cpp.i
.PHONY : src/renderer.cpp.i

src/renderer.s: src/renderer.cpp.s
.PHONY : src/renderer.s

# target to generate assembly for a file
src/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/renderer.cpp.s
.PHONY : src/renderer.cpp.s

src/resources/buffer.o: src/resources/buffer.cpp.o
.PHONY : src/resources/buffer.o

# target to build an object file
src/resources/buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/resources/buffer.cpp.o
.PHONY : src/resources/buffer.cpp.o

src/resources/buffer.i: src/resources/buffer.cpp.i
.PHONY : src/resources/buffer.i

# target to preprocess a source file
src/resources/buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/resources/buffer.cpp.i
.PHONY : src/resources/buffer.cpp.i

src/resources/buffer.s: src/resources/buffer.cpp.s
.PHONY : src/resources/buffer.s

# target to generate assembly for a file
src/resources/buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/resources/buffer.cpp.s
.PHONY : src/resources/buffer.cpp.s

src/shader_loader.o: src/shader_loader.cpp.o
.PHONY : src/shader_loader.o

# target to build an object file
src/shader_loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/shader_loader.cpp.o
.PHONY : src/shader_loader.cpp.o

src/shader_loader.i: src/shader_loader.cpp.i
.PHONY : src/shader_loader.i

# target to preprocess a source file
src/shader_loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/shader_loader.cpp.i
.PHONY : src/shader_loader.cpp.i

src/shader_loader.s: src/shader_loader.cpp.s
.PHONY : src/shader_loader.s

# target to generate assembly for a file
src/shader_loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/shader_loader.cpp.s
.PHONY : src/shader_loader.cpp.s

src/ui/csv_editor.o: src/ui/csv_editor.cpp.o
.PHONY : src/ui/csv_editor.o

# target to build an object file
src/ui/csv_editor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/ui/csv_editor.cpp.o
.PHONY : src/ui/csv_editor.cpp.o

src/ui/csv_editor.i: src/ui/csv_editor.cpp.i
.PHONY : src/ui/csv_editor.i

# target to preprocess a source file
src/ui/csv_editor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/ui/csv_editor.cpp.i
.PHONY : src/ui/csv_editor.cpp.i

src/ui/csv_editor.s: src/ui/csv_editor.cpp.s
.PHONY : src/ui/csv_editor.s

# target to generate assembly for a file
src/ui/csv_editor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/ui/csv_editor.cpp.s
.PHONY : src/ui/csv_editor.cpp.s

src/ui/file_browser.o: src/ui/file_browser.cpp.o
.PHONY : src/ui/file_browser.o

# target to build an object file
src/ui/file_browser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/ui/file_browser.cpp.o
.PHONY : src/ui/file_browser.cpp.o

src/ui/file_browser.i: src/ui/file_browser.cpp.i
.PHONY : src/ui/file_browser.i

# target to preprocess a source file
src/ui/file_browser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/ui/file_browser.cpp.i
.PHONY : src/ui/file_browser.cpp.i

src/ui/file_browser.s: src/ui/file_browser.cpp.s
.PHONY : src/ui/file_browser.s

# target to generate assembly for a file
src/ui/file_browser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/ui/file_browser.cpp.s
.PHONY : src/ui/file_browser.cpp.s

src/vulkan_context.o: src/vulkan_context.cpp.o
.PHONY : src/vulkan_context.o

# target to build an object file
src/vulkan_context.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/vulkan_context.cpp.o
.PHONY : src/vulkan_context.cpp.o

src/vulkan_context.i: src/vulkan_context.cpp.i
.PHONY : src/vulkan_context.i

# target to preprocess a source file
src/vulkan_context.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/vulkan_context.cpp.i
.PHONY : src/vulkan_context.cpp.i

src/vulkan_context.s: src/vulkan_context.cpp.s
.PHONY : src/vulkan_context.s

# target to generate assembly for a file
src/vulkan_context.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/vulkan_context.cpp.s
.PHONY : src/vulkan_context.cpp.s

src/world.o: src/world.cpp.o
.PHONY : src/world.o

# target to build an object file
src/world.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/world.cpp.o
.PHONY : src/world.cpp.o

src/world.i: src/world.cpp.i
.PHONY : src/world.i

# target to preprocess a source file
src/world.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/world.cpp.i
.PHONY : src/world.cpp.i

src/world.s: src/world.cpp.s
.PHONY : src/world.s

# target to generate assembly for a file
src/world.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/src/world.cpp.s
.PHONY : src/world.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... shaders_spirv"
	@echo "... hello"
	@echo "... imgui/backends/imgui_impl_sdl2.o"
	@echo "... imgui/backends/imgui_impl_sdl2.i"
	@echo "... imgui/backends/imgui_impl_sdl2.s"
	@echo "... imgui/backends/imgui_impl_vulkan.o"
	@echo "... imgui/backends/imgui_impl_vulkan.i"
	@echo "... imgui/backends/imgui_impl_vulkan.s"
	@echo "... imgui/imgui.o"
	@echo "... imgui/imgui.i"
	@echo "... imgui/imgui.s"
	@echo "... imgui/imgui_demo.o"
	@echo "... imgui/imgui_demo.i"
	@echo "... imgui/imgui_demo.s"
	@echo "... imgui/imgui_draw.o"
	@echo "... imgui/imgui_draw.i"
	@echo "... imgui/imgui_draw.s"
	@echo "... imgui/imgui_tables.o"
	@echo "... imgui/imgui_tables.i"
	@echo "... imgui/imgui_tables.s"
	@echo "... imgui/imgui_widgets.o"
	@echo "... imgui/imgui_widgets.i"
	@echo "... imgui/imgui_widgets.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/core/application.o"
	@echo "... src/core/application.i"
	@echo "... src/core/application.s"
	@echo "... src/core/command_pool.o"
	@echo "... src/core/command_pool.i"
	@echo "... src/core/command_pool.s"
	@echo "... src/core/graphics_context.o"
	@echo "... src/core/graphics_context.i"
	@echo "... src/core/graphics_context.s"
	@echo "... src/core/job_system.o"
	@echo "... src/core/job_system.i"
	@echo "... src/core/job_system.s"
	@echo "... src/core/swapchain.o"
	@echo "... src/core/swapchain.i"
	@echo "... src/core/swapchain.s"
	@echo "... src/core/sync_objects.o"
	@echo "... src/core/sync_objects.i"
	@echo "... src/core/sync_objects.s"
	@echo "... src/graphics/camera.o"
	@echo "... src/graphics/camera.i"
	@echo "... src/graphics/camera.s"
	@echo "... src/graphics/geometry_utils.o"
	@echo "... src/graphics/geometry_utils.i"
	@echo "... src/graphics/geometry_utils.s"
	@echo "... src/graphics/material.o"
	@echo "... src/graphics/material.i"
	@echo "... src/graphics/material.s"
	@echo "... src/graphics/mesh.o"
	@echo "... src/graphics/mesh.i"
	@echo "... src/graphics/mesh.s"
	@echo "... src/graphics/shader.o"
	@echo "... src/graphics/shader.i"
	@echo "... src/graphics/shader.s"
	@echo "... src/imgui_backend.o"
	@echo "... src/imgui_backend.i"
	@echo "... src/imgui_backend.s"
	@echo "... src/init_sdl.o"
	@echo "... src/init_sdl.i"
	@echo "... src/init_sdl.s"
	@echo "... src/math/analysis.o"
	@echo "... src/math/analysis.i"
	@echo "... src/math/analysis.s"
	@echo "... src/math/pcoa.o"
	@echo "... src/math/pcoa.i"
	@echo "... src/math/pcoa.s"
	@echo "... src/renderer.o"
	@echo "... src/renderer.i"
	@echo "... src/renderer.s"
	@echo "... src/resources/buffer.o"
	@echo "... src/resources/buffer.i"
	@echo "... src/resources/buffer.s"
	@echo "... src/shader_loader.o"
	@echo "... src/shader_loader.i"
	@echo "... src/shader_loader.s"
	@echo "... src/ui/csv_editor.o"
	@echo "... src/ui/csv_editor.i"
	@echo "... src/ui/csv_editor.s"
	@echo "... src/ui/file_browser.o"
	@echo "... src/ui/file_browser.i"
	@echo "... src/ui/file_browser.s"
	@echo "... src/vulkan_context.o"
	@echo "... src/vulkan_context.i"
	@echo "... src/vulkan_context.s"
	@echo "... src/world.o"
	@echo "... src/world.i"
	@echo "... src/world.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

